#关闭缓存，即时刷新
spring:
  thymeleaf:
    cache: true
  #热部署生效
  devtools:
    restart:
      enabled: true
      #设置重启目录（监听需要restart的文件）
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://localhost:3306/outsources?characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #邮件配置
  mail:
    host: smtp.163.com
    username: m15809273850@163.com
    password: 19951228jcx
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: utf-8
  freemarker:
    content-type: text/html
    #后缀名
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
#设置一个邮件发送人
lance:
  mail:
    sender: m15809273850@163.com
mybatis:
  config-location: mybatis-config.xml
  mapper-locations: /mapper/**.xml
  type-aliases-package: com.xdkj.outsources.entity


